import time

from selenium import webdriver
from selenium.webdriver.common.by import By


class Admin_locators:
    admin_url = "https://qa-admin.trado.co.il/#/"
    product_XPATH = "//body/div[@id='root']/div[1]/div[2]/div[1]/nav[1]/div[2]/a[2]"
    sales_XPATH = "//span[contains(text(),'מבצעים')]"
    coupon_XPATH = "//span[contains(text(),'קופונים')]"
    orders_XPATH = "//span[contains(text(),'הזמנות')]"
    invoices_XPATH = "//span[contains(text(),'חשבוניות')]"
    shipping_certificates_XPATH = "//span[contains(text(),'תעודת משלוח')]"
    shipping_dashboard_XPATH = "//span[contains(text(),'דשבורד משלוחים')]"
    shipping_tables_XPATH = "//span[contains(text(),'טבלת משלוחים')]"
    review_purchases_XPATH = "//span[contains(text(),'סקירת רכישות')]"
    review_monthly_XPATH = "//label[contains(text(),'Monthly')]"
    review_daily_XPATH = "//label[contains(text(),'יומי')]"
    audience_review_XPATH = "//span[contains(text(),'סקירת קהלים')]"
    reviewing_behaviors_XPATH = "//span[contains(text(),'סקירת התנהגויות')]"
    overview_XPATH = "//span[contains(text(),'סקירה כללית')]"
    dashboard_XPATH = "//body/div[@id='root']/div[1]/div[2]/div[1]/nav[1]/div[2]/a[14]/span[2]"
    reports_XPATH = "//span[contains(text(),'דיווחים')]"
    date_display_ID = "//div[@id='date_displey']"
    alerts_XPATH = "//span[contains(text(),'התראות')]"
    objectives_XPATH = "//span[contains(text(),'יעדים')]"
    finanec_XPATH = "//span[contains(text(),'פיננסים')]"
    etrado_XPATH = "//span[contains(text(),'eTrado')]"
    departement_XPATH = "//span[contains(text(),'מחלקות')]"
    catagory_XPATH = "//span[contains(text(),'קטגוריות')]"
    stores_XPATH = "//span[contains(text(),'חנויות')]"
    users_XPATH = "//span[contains(text(),'משתמשים')]"
    user_system_XPATH = "//span[contains(text(),'משתמשי מערכת')]"
    hand_outs_XPATH = "//span[contains(text(),'דפי מידע')]"
    setting_XPATH = "//span[contains(text(),'הגדרות')]"
    records_XPATH = "//body/div[@id='root']/div[1]/div[2]/div[1]/nav[1]/div[2]/a[27]"
    option1_xpath = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    click_xpath = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    option2_xpath = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    login_button = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    dashboard_coupon_XPATH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/a[1]"
    dashboard_finances_1_XPATH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/a[2]"
    dashboard_orders_XPATH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/a[3]"
    dashboard_sales_XPATH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/a[5]"
    dashboard_product_XPATH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/a[4]"
    dashboard_stores_XPATH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/a[6]"
    dashboard_users_XPATH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/a[7]"
    dashboard_finances_2_XPATH = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/a[8]"
    dashboard_button_xpath = "//body/div[@id='root']/div[1]/div[2]/div[1]/nav[1]/div[2]/a[1]"

