class AdminProductLocators:
    website = "https://qa-admin.trado.co.il/"
    phone_xpath = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    click_xpath = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    code_xpath = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]"
    login_button = "//body/div[@id='root']/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]"
    product_button_xpath = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/a[4]/span[1]"
    single_next_arrow_xpath = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[4]/i[1]"
    double_next_arrow_xpath = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[5]/i[1]"
    double_back_arrow_xpath = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[1]/i[1]"
    amount_Display = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[1]"
    amount_xpath = "//div[contains(text(),'100')]"
    add_xpath = "//body/div[@id='root']/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[1]/span[1]/i[1]"
    add_product_xpath = "//span[contains(text(),'הוספה')]"
    bar_code_xpath = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[2]/span[1]/div[1]/input[1]"
    name_xpath = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[4]/span[1]/div[1]/input[1]"
    price_xpath = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[5]/span[1]/div[1]/input[1]"
    date_xpath = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[7]/span[1]/div[1]/input[1]"
    description_xpath = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[8]/span[1]/div[1]/input[1]"
    next_xpath = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[4]/input[1]"
    product_search_xpath = "//body/div[@id='root']/div[1]/div[4]/div[1]/div[1]/span[1]/form[1]/div[2]/div[1]/div[1]/span[1]/span[1]/div[1]/input[1]"
    us_language_xpath = "//span[contains(text(),'🇺🇸')]"
    Il_language_xpath = "//span[contains(text(),'🇮🇱')]"

