class Constant_department_search():
    url = "https://qa-api.trado.co.il/api/department/filter"
    valid_data = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"u6z3r13kkkv9cqk3","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    invalid_non_existing = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"k82exhzh2bz2h2dg","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    invalid_special_character =  '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"#$%^^**&(&(","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    null_search_bar =  '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    insert_only_numbers = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"7662626221","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    insert_single_letter = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"u","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    search_multiple_words = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"dave dave","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    miss_spelling_words = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"z3r13kkkv9cqk3","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    search_UPPERCASE_letter = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"U6Z3R13KKKV9CQK3","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    search_LOWER_case = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"tftfytf7r6fu","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    search_product_mix_UPPER_and_LOWER_case = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"U6Z3r13kKkv9cQk3","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'
    search_mix_upper_lower_special_letter = '{"from":0,"limit":50,"sort":{"order":1},"filter":{},"search":"u63r13kKkv@#qk3","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/departments","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/departments"}}}'









