class ConstantSearchOrders:
    url = "https://qa-api.trado.co.il/api/order/filter"
    valid_data = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"peace","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    invalid_non_existing = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"fshdwqgdwekufhgwei","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    invalid_special_character = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"":"@#$%^&**","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    null_search_bar = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    insert_only_numbers = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"123","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    insert_single_letter = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"b","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    search_multiple_words = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"milk milk","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    misspeling_words = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"mil","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    search_UPPERCASE_letter = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"MILK","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    search_LOWER_case = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"milk-goat","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    search_product_mix_UPPER_and_LOWER_case = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"MILK-goat","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'
    search_mix_upper_lower_special_letter = '{"from":0,"limit":50,"sort":{"createdAt":-1},"filter":{"status":"received"},"productsList":true,"search":"MILK-goat @#$%,"info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":871,"screenWidth":1549,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/orders","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/orders"}}}'


