class Constantsearchusers():
    url = "https://qa-api.trado.co.il/api/admin-user/filter"
    valid_data = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"slamonnn","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    invalid_non_existing = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"drake","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    invalid_special_character = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"#$%^^**&(&(","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    null_search_bar = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    insert_only_numbers = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"1234567","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    insert_single_letter = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"a","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    search_multiple_words = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"slamonnn slamonnn","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    miss_spelling_words = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"nnnomals","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    search_UPPERCASE_letter = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"SLAMONNN","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    search_LOWER_case = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"slamonnn","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    search_product_mix_UPPER_and_LOWER_case = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"SLAMonnn","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
    search_mix_upper_lower_special_letter = '{"from":0,"limit":50,"sort":{"lastSeen":-1},"filter":{},"search":"SLAmon@#","info":{"uid":"pslie6ckppafmkm","sid":"1010101011rh","lng":"hebrew","getTypes":true,"platform":"admin","isMobile":false,"screenHeight":864,"screenWidth":1536,"location":{"ancestorOrigins":{},"href":"https://qa-admin.trado.co.il/#/admin-users","origin":"https://qa-admin.trado.co.il","protocol":"https:","host":"qa-admin.trado.co.il","hostname":"qa-admin.trado.co.il","port":"","pathname":"/","search":"","hash":"#/admin-users"}}}'
